"""Tests for adoc.ingest.filetypes.detect_intake_kind - the intake
detection matrix (genomics/filetypes task item 6): pdf, docx (checked
before zip), text (with the oversized-rejection boundary drawn in
`ingest.archive`, not here), genomic (23andMe txt sniff, BGZF .bcf, plain
.vcf, FASTQ), and zip.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

from conftest import TINY_PDF_BYTES
from docx import Document

from adoc.ingest.filetypes import detect_intake_kind

BGZF_MAGIC = bytes.fromhex("1f8b0804")


def test_detects_pdf_by_magic(tmp_path: Path) -> None:
    path = tmp_path / "doc.pdf"
    path.write_bytes(TINY_PDF_BYTES)
    assert detect_intake_kind(path) == "pdf"


def test_detects_a_real_docx_package(tmp_path: Path) -> None:
    path = tmp_path / "notes.docx"
    document = Document()
    document.add_paragraph("hello")
    document.save(str(path))

    assert detect_intake_kind(path) == "docx"


def test_rejects_a_fake_pk_header_without_a_real_zip(tmp_path: Path) -> None:
    """A file merely renamed to `.docx` with a spoofed zip magic, but not an
    actual zip archive, must never be treated as a real docx package."""
    path = tmp_path / "notes.docx"
    path.write_bytes(b"PK\x03\x04 not a real zip at all")

    assert detect_intake_kind(path) is None


def test_rejects_a_real_zip_without_content_types(tmp_path: Path) -> None:
    """A real zip archive that isn't an OOXML package (no
    `[Content_Types].xml`) must not be misdetected as docx even with the
    `.docx` suffix - and since the suffix isn't `.zip`, it isn't picked up
    by the generic zip branch either."""
    path = tmp_path / "notes.docx"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("readme.txt", "just a plain zip")

    assert detect_intake_kind(path) is None


def test_docx_content_saved_with_zip_suffix_is_a_generic_zip_not_docx(tmp_path: Path) -> None:
    """docx detection is gated on BOTH the `.docx` suffix AND the
    `[Content_Types].xml` manifest (checked before the zip branch, per the
    module docstring) - a real OOXML package saved with a `.zip` suffix is
    correctly a generic zip archive to expand, not a docx (and not
    rejected either, now that zip archives are a supported intake kind)."""
    path = tmp_path / "notes.zip"
    document = Document()
    document.add_paragraph("hello")
    document.save(str(path))

    assert detect_intake_kind(path) == "zip"


def test_rejects_unrelated_file_types(tmp_path: Path) -> None:
    path = tmp_path / "notes.png"
    path.write_bytes(b"\x89PNG\r\n\x1a\nnot really a png")

    assert detect_intake_kind(path) is None


def test_rejects_a_missing_file_without_raising(tmp_path: Path) -> None:
    assert detect_intake_kind(tmp_path / "missing.pdf") is None


# --------------------------------------------------------------------------
# text
# --------------------------------------------------------------------------


def test_detects_a_plain_txt_narrative_as_text(tmp_path: Path) -> None:
    path = tmp_path / "history.txt"
    path.write_text("Patient-authored clinical history.\n", encoding="utf-8")

    assert detect_intake_kind(path) == "text"


def test_detects_a_plain_md_narrative_as_text(tmp_path: Path) -> None:
    path = tmp_path / "history.md"
    path.write_text("# Clinical history\n\nOnset in March.\n", encoding="utf-8")

    assert detect_intake_kind(path) == "text"


# --------------------------------------------------------------------------
# genomic - never enters the LLM document pipeline
# --------------------------------------------------------------------------


def test_detects_a_23andme_style_raw_export_as_genomic(tmp_path: Path) -> None:
    path = tmp_path / "genome_First_Last.txt"
    path.write_text(
        "# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2026\n"
        "# Below is a text version of your data.\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs4477212\t1\t82154\tAA\n"
        "rs3094315\t1\t752566\tAG\n",
        encoding="utf-8",
    )

    assert detect_intake_kind(path) == "genomic"


def test_detects_a_23andme_export_with_an_uncommented_rsid_header(tmp_path: Path) -> None:
    """The header line itself may or may not be commented - both count."""
    path = tmp_path / "genome_First_Last.txt"
    path.write_text(
        "# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2026\n"
        "rsid\tchromosome\tposition\tgenotype\n"
        "rs4477212\t1\t82154\tAA\n",
        encoding="utf-8",
    )

    assert detect_intake_kind(path) == "genomic"


def test_a_txt_file_with_an_rsid_header_but_no_leading_comment_block_is_plain_text(
    tmp_path: Path,
) -> None:
    """The spec is "a leading `# ` comment block FOLLOWED BY" the header -
    a bare rsid table with no comment block first is not sniffed as a
    23andMe export (it just falls through to ordinary "text")."""
    path = tmp_path / "table.txt"
    path.write_text("rsid\tchromosome\tposition\tgenotype\nrs1\t1\t1\tAA\n", encoding="utf-8")

    assert detect_intake_kind(path) == "text"


def test_a_txt_file_with_unrelated_content_after_comments_is_plain_text(tmp_path: Path) -> None:
    path = tmp_path / "notes.txt"
    path.write_text("# just a comment\nsome unrelated narrative text\n", encoding="utf-8")

    assert detect_intake_kind(path) == "text"


def test_detects_a_bgzf_bcf_file_as_genomic(tmp_path: Path) -> None:
    path = tmp_path / "chr1.imputed.bcf"
    path.write_bytes(BGZF_MAGIC + b"\x00" * 32)

    assert detect_intake_kind(path) == "genomic"


def test_detects_a_bgzf_vcf_gz_file_as_genomic(tmp_path: Path) -> None:
    path = tmp_path / "sample.vcf.gz"
    path.write_bytes(BGZF_MAGIC + b"\x00" * 32)

    assert detect_intake_kind(path) == "genomic"


def test_a_gzip_file_with_an_unrelated_suffix_is_not_genomic(tmp_path: Path) -> None:
    path = tmp_path / "archive.tar.gz"
    path.write_bytes(BGZF_MAGIC + b"\x00" * 32)

    assert detect_intake_kind(path) is None


def test_detects_a_plain_vcf_by_its_fileformat_header(tmp_path: Path) -> None:
    path = tmp_path / "sample.vcf"
    path.write_bytes(b"##fileformat=VCFv4.2\n#CHROM\tPOS\tID\n1\t123\trs1\n")

    assert detect_intake_kind(path) == "genomic"


def test_a_vcf_suffixed_file_without_the_real_header_is_not_genomic(tmp_path: Path) -> None:
    path = tmp_path / "sample.vcf"
    path.write_bytes(b"not actually a vcf file at all\n")

    assert detect_intake_kind(path) is None


def test_detects_a_plain_fastq_file_as_genomic(tmp_path: Path) -> None:
    path = tmp_path / "reads.fastq"
    path.write_bytes(b"@SEQ_ID\nGATTACA\n+\n!!!!!!!\n")

    assert detect_intake_kind(path) == "genomic"


# --------------------------------------------------------------------------
# zip
# --------------------------------------------------------------------------


def test_detects_a_plain_zip_archive(tmp_path: Path) -> None:
    path = tmp_path / "bundle.zip"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("a.txt", "hello")

    assert detect_intake_kind(path) == "zip"
